POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### 
POST http://localhost:3000/auth
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2NzE2NTQ0NzJ9.K6LKBPdbs7_u9SJtXhb4n4ckXO-a71GaN8Kt3UzOsCc"
}

### 
POST http://localhost:3000/auth
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGciLCJpYXQiOjE2NzE2NTQ0NzJ9.msV15U5m3Ypj-gFMiBxIwWGFh_NaGtyOyIhtecrXy-Q"
}